### ISSUE TITLE
Weather Application

### ISSUE THREAD

**Issue by quindariuss** [MasonMcCool/MasonMcCool.github.io#2]
# You will be creating a weather app on your website

## Tasks

- [x] Create a subpage on your website for users to navigate to. It should look like: 
> https://masonmccool.com/weatherapp
```html
<a href="websitelink">Subpage</a>
```

- [ ] Get the weather for Milton Ga and display it on the website

- [ ] Show the user all the information from the API 

- [ ] Design the page with CSS

**Comment by quindariuss** [comment]
add some id variables to the weather app html elements

'''html 
<h1 id="temperature"></h1>
'''
